<a href="https://colab.research.google.com/github/saisohanallam/ML_LAB_2026-27/blob/main/ML_LAB_EXP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

In [1]:
import pandas as pd

**Importing CSV files**

Use read_csv() with the path to the CSV file to read a comma-separated values file

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [5]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [6]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [7]:
df = pd.read_excel("student_dataset.xlsx", sheet_name="Student_Data")

In [12]:
df.head()

,RollNo,Name,Branch,Math,Physics,Chemistry,Programming,Total_Marks,Percentage
0,101,Aarav Sharma,Computer Science,85,80,88,95,348,87.00
1,102,Vivaan Singh,Electrical,78,82,79,70,309,77.25
2,103,Aditya Patel,Mechanical,92,89,90,85,356,89.00
3,104,Vihaan Kumar,Computer Science,65,60,62,80,267,66.75
4,105,Arjun Gupta,Civil,74,71,75,65,285,71.25

In [13]:
df.tail()

,RollNo,Name,Branch,Math,Physics,Chemistry,Programming,Total_Marks,Percentage
5,106,Sai Iyer,Electrical,88,85,82,75,330,82.50
6,107,Ayaan Desai,Computer Science,95,91,94,98,378,94.50
7,108,Krishna Reddy,Mechanical,70,68,72,60,270,67.50
8,109,Ishaan Verma,Civil,60,65,63,55,243,60.75
9,110,Shaurya Bose,Computer Science,89,87,85,92,353,88.25

In [14]:
df.describe()

,RollNo,Math,Physics,Chemistry,Programming,Total_Marks,Percentage
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,105.50000,79.600000,77.800000,79.000000,77.500000,313.900000,78.475000
std,3.02765,12.029593,10.962563,10.964589,15.020357,45.758909,11.439727
min,101.00000,60.000000,60.000000,62.000000,55.000000,243.000000,60.750000
25%,103.25000,71.000000,68.750000,72.750000,66.250000,273.750000,68.437500
50%,105.50000,81.500000,81.000000,80.500000,77.500000,319.500000,79.875000
75%,107.75000,88.750000,86.500000,87.250000,90.250000,351.750000,87.937500
max,110.00000,95.000000,91.000000,94.000000,98.000000,378.000000,94.500000

In [15]:
df.columns

Index(['RollNo', 'Name', 'Branch', 'Math', 'Physics', 'Chemistry',
       'Programming', 'Total_Marks', 'Percentage'],
      dtype='object')